In [9]:
from utils import *

np.set_printoptions(precision=3, suppress=True)

Ns_array = [4, -4, 3, 5, -5]

# vec = linear_chain_DMI_coeffs_vector(4)
max_d_order = 8

M = coeff_matrix(Ns_array, max_d_order=max_d_order)
# print(M)
M_partially_diagonalized, M_sub_inv = diagonalize_coefficient_matrix(M)

In [10]:
print("obtained terms")
print(M_partially_diagonalized)

obtained terms
[[ 1.327 -0.142  0.037  0.106 -0.037 -0.069  0.     0.069  0.037]
 [ 0.     0.366  0.197  0.173 -0.516 -0.866  0.731  1.297 -0.656]
 [-1.375  0.267  0.233 -0.517 -0.365  0.733  0.028 -0.865  0.256]
 [-0.062 -0.272 -0.041  1.048 -0.279 -1.978  0.731  2.409 -0.956]
 [-0.25  -0.5   -0.25  -0.065  0.5    0.75  -0.703 -1.25   0.75 ]]


In [11]:
print("summing coefficients")
print(M_sub_inv)

summing coefficients
[[ 5.475e-02  8.115e-02  1.236e-01  2.194e-17  1.377e-01]
 [-1.613e+14 -1.613e+14  2.150e+14  1.538e-01  2.150e+14]
 [-5.835e+14 -5.835e+14  7.780e+14  5.864e-03  7.780e+14]
 [-1.613e+14 -1.613e+14  2.150e+14  1.538e-01  2.150e+14]
 [-4.222e+14 -4.222e+14  5.629e+14 -1.479e-01  5.629e+14]]


In [12]:
explain_results(M_sub_inv, M_partially_diagonalized, Ns_array)

Having calculated the DFT total energies for supercells (4, -4, 3, 5, -3), corresponding to angles (90.0, -90.0, 120.0, 72.0, -120.0) degrees, 
                we obtain the ground-state energy E0 and the DMI coefficients d_n up to order n_max = 8
                  with the following formulas:
E0 = 0.055 E(4) + 0.081 E(-4) + 0.124 E(3) + 0.138 E(-3)
0.366 d_1 + 0.197 d_2 + 0.173 d_3 + -0.516 d_4 + -0.866 d_5 + 0.731 d_6 + 1.297 d_7 + -0.656 d_8 = -161270811181328.094 E(4) + -161270811181327.938 E(-4) + 215027748241770.594 E(3) + 0.154 E(5) + 215027748241770.500 E(-3)
0.267 d_1 + 0.233 d_2 + -0.517 d_3 + -0.365 d_4 + 0.733 d_5 + 0.028 d_6 + -0.865 d_7 + 0.256 d_8 = -583483276247312.125 E(4) + -583483276247312.250 E(-4) + 777977701663082.750 E(3) + 0.006 E(5) + 777977701663082.875 E(-3)
-0.272 d_1 + -0.041 d_2 + 1.048 d_3 + -0.279 d_4 + -1.978 d_5 + 0.731 d_6 + 2.409 d_7 + -0.956 d_8 = -161270811181328.094 E(4) + -161270811181327.719 E(-4) + 215027748241770.500 E(3) + 0.154 E(5) + 215027