# $J_{x,y}$, $J_z$ and $K_\mathrm{u}$ calculation from total energy
## Hexagonal mesh (1T-TMDs)

In [1]:
from totEnJ.utils import *
np.set_printoptions(precision=3, suppress=True)

Define the 
* supercell size $n_x$ in the DFT calculations and 
* the maximum number of nearest-neighbors considered (not implemented yet)

In [2]:
# supercell size in x
nx = 3

# maximum order of nearest-neighbors; 5 is probably more than enough (physically)
max_d_order = 5

Construct total energy expressions for all spin spirals (express as a matrix) \
and diagonalize the square submatrix of this rectangular matrix.

In [3]:
M, *states = coeff_matrix_Jxy_Jz_K(order_NN=5)
print('- M matrix:\n', M)
print('\n- states:\n', states)
M_partially_diagonalized, M_sub_inv = diagonalize_coefficient_matrix(M)

- M matrix:
 [[  1   0 -24   0 -24   0 -24   0 -48   0 -24   0]
 [  1   0  -8   0   0   0  -8   0   0   0  -8   0]
 [  1   0  -8   0   0   0  -8   0   0   0  -8   0]
 [  1   0  -8   0   8   0   8   0  16   0  -8   0]
 [  1   0  -8   0   0   0  -8   0   0   0  -8   0]
 [  1   0   8   0   8   0 -24   0  16   0   8   0]
 [  1   0  -8   0   8   0   8   0  16   0  -8   0]
 [  1   0  -8   0   0   0  -8   0   0   0  -8   0]
 [  1  -4   0 -24   0 -24   0 -24   0 -48   0 -24]
 [  1  -4   0  -8   0   0   0  -8   0   0   0  -8]
 [  1  -4   0  -8   0   0   0  -8   0   0   0  -8]
 [  1  -4   0  -8   0   8   0   8   0  16   0  -8]
 [  1  -4   0  -8   0   0   0  -8   0   0   0  -8]
 [  1  -4   0   8   0   8   0 -24   0  16   0   8]
 [  1  -4   0  -8   0   8   0   8   0  16   0  -8]
 [  1  -4   0  -8   0   0   0  -8   0   0   0  -8]]

- states:
 [array([[ 0,  1,  1,  1,  1],
       [ 0,  1,  1,  1, -1],
       [ 0,  1,  1, -1,  1],
       [ 0,  1,  1, -1, -1],
       [ 0,  1, -1,  1,  1],
       [ 0, 

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
print("with DFT supercell sizes")
print(nx)

print('')

print("we obtain linear combinations of terms")
print(['E0', 'Ku'] + [J for n in range(1, max_d_order+1) for J in [f'J_x{n:d}', f'J_z{n:d}']])

print('')

print('combined in the following way')
print(M_partially_diagonalized)

print('')

print("by summing the energies E(cz, m1, m2, ...)")
print([f"E({', '.join([str(cz_or_m)])})" for state in states for cz_or_m in state])

print('')

print("with prefactor coefficients")
print(M_sub_inv)

with DFT supercell sizes
[-4, 4, 3, 5, 6]

we obtain linear combinations of terms
['E0', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8']

combined in the following way
[[ 1.     0.     0.    -0.    -0.    -0.     0.     0.    -0.   ]
 [ 0.     1.     0.     0.    -0.    -1.     0.     1.    -0.   ]
 [-0.     0.     1.    -0.     0.     0.618 -2.618 -2.236  4.236]
 [ 0.     0.     0.     1.    -0.    -2.     0.     2.    -0.   ]
 [-0.     0.    -0.    -0.     1.     0.618 -2.618 -2.236  3.236]]

by summing the energies
['E(-4)', 'E(4)', 'E(3)', 'E(5)', 'E(6)']

with prefactor coefficients
[[ 0.125  0.125 -0.     0.     0.   ]
 [-0.144 -0.144  0.192  0.     0.096]
 [-0.002  0.402 -0.311 -0.551  0.348]
 [-0.019 -0.269  0.192  0.     0.096]
 [-0.002  0.402 -0.119 -0.551  0.252]]


In [ ]:
explain_results_verbose(M_sub_inv, M_partially_diagonalized, Ns_array)

Having calculated the DFT total energies for supercells (-4, 4, 3, 5, 6), corresponding to angles (-90.0, 90.0, 120.0, 72.0, 60.0) degrees, 
                we obtain the ground-state energy E0 and the DMI coefficients d_n up to order n_max = 8
                  with the following formulas:
E0 = 0.125 E(-4) + 0.125 E(4)
1.000 d_1 + -1.000 d_5 + 0.000 d_6 + 1.000 d_7 + -0.000 d_8 = -0.144 E(-4) + -0.144 E(4) + 0.192 E(3) + 0.000 E(5) + 0.096 E(6)
1.000 d_2 + -0.000 d_3 + 0.618 d_5 + -2.618 d_6 + -2.236 d_7 + 4.236 d_8 = -0.002 E(-4) + 0.402 E(4) + -0.311 E(3) + -0.551 E(5) + 0.348 E(6)
1.000 d_3 + -2.000 d_5 + 0.000 d_6 + 2.000 d_7 + -0.000 d_8 = -0.019 E(-4) + -0.269 E(4) + 0.192 E(3) + 0.000 E(5) + 0.096 E(6)
1.000 d_4 + 0.618 d_5 + -2.618 d_6 + -2.236 d_7 + 3.236 d_8 = -0.002 E(-4) + 0.402 E(4) + -0.119 E(3) + -0.551 E(5) + 0.252 E(6)
